url: https://rowerunning.co.uk
name: Rowe Running
description: The adventures of David, Sharon and a little running, triathlon and Ironman exploits...
title: Rowe Running

excerpts: true
exclude:
  - "*.gemspec"
  - "CONTRIBUTING*"
  - "Gemfile*"
  - "LICENSE*"
  - "README*"
  - "wordpress-exports*"

paginate: 5
paginate_path: /pages/:num/
permalink: /:year/:month/:title/
plugins:
  - jekyll-paginate

# Filtering Content https://jekyllrb.com/docs/configuration/default/
future: true

defaults:
  - scope:
      path: ""
      type: posts # an empty string here means all files in the project
    values:
      layout: post
      is_post: true # https://conductofcode.io/post/social-meta-tags-with-jekyll/


gtag: UA-70634-8

date_format: "%-d %B %Y"
date_format_no_year: "%-d %B"

# disqus_shortname: rowerunning